$ANSIBLE_VAULT;1.1;AES256
30373737316632643732643561626636386663323337626565393133623930313161646632396666
6561626436316236383066373331363265353466333936380a663865666537643666626332343762
66633434313337633362316638666132643033356165313632666561616438396537366232623133
3134666538303136660a313735393438616665366263643664396163303035346536653663363933
34643032343365656166653065643537623436353866633365396538656332373436366434343538
36616131613961323733313534346531323333383737663631323138343666313866663365343766
346332383537666335393731666365313663
