---
- name: Add Prometheus Community Helm Repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Create Configuration Values
  ansible.builtin.template:
    src: values.yaml.j2
    dest: /tmp/monitoring-values.yaml

- name: Deploy Kube-Prometheus-Stack
  kubernetes.core.helm:
    name: monitoring
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: "{{ monitoring_namespace }}"
    create_namespace: true
    values_files:
      - /tmp/monitoring-values.yaml
    kubeconfig: /etc/rancher/k3s/k3s.yaml