$ANSIBLE_VAULT;1.1;AES256
65323063383831643533383738613663323234633138623261313631306539343139666531346336
6264663430346235333762623436663065613431626232380a316535346433383266653362333333
62373330633633393163653266633337626165363636666237356565353438353938373963653737
3638646666333661350a303566633262353839313433613761636337666432393665343865306463
66363663353339363733303131613839653234396361616164386536313066396537363636616465
6361616335396532346439393336646138613932613032616666
