$ANSIBLE_VAULT;1.1;AES256
66626661653137653065613933376236376165353330653836383661653961656566393931353631
6431383736636536393066333836373761613465383763330a663161346539346638336432633864
38326234646231643362363566653232353062643465396262363061386435346234616266373230
3037313166646164320a313737396630333530623430333262376666353064633435333463386335
33666237346238613962336263646162633566303330303035666139633562633762613266346433
3963373262656536316237343239383735383437656635393666
